services:
  semaphore-kubespray:
    build:
      args:
        KUBESPRAY_REF: ${KUBESPRAY_REF}
    environment:
      KUBESPRAY_DIR: /opt/kubespray
    volumes:
      - /opt/eclipse-cluster-config:/opt/eclipse-cluster-config
